export const RECV_ERROR = 'RECV_ERROR';
export const REQ_SENSORS = 'REQ_SENSORS';
export const RECV_SENSORS = 'RECV_SENSORS';
export const CREATE_SENSORS_START = 'CREATE_SENSORS_START';
export const CREATE_SENSORS_SUCCESS = 'CREATE_SENSORS_SUCCESS';
export const CREATE_SENSORS_ERROR = 'CREATE_SENSORS_ERROR';
