# coding: utf-8

"""
    WAZIUP API

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class MeasureMetadata(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, unit=None, timestamp=None, dimension=None):
        """
        MeasureMetadata - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'unit': 'str',
            'timestamp': 'str',
            'dimension': 'str'
        }

        self.attribute_map = {
            'unit': 'unit',
            'timestamp': 'timestamp',
            'dimension': 'str'
        }

        self._unit = unit
        self._timestamp = timestamp
        self._dimension = dimension

    @property
    def unit(self):
        """
        Gets the unit of this MeasureMetadata.


        :return: The unit of this MeasureMetadata.
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit):
        """
        Sets the unit of this MeasureMetadata.


        :param unit: The unit of this MeasureMetadata.
        :type: str
        """

        self._unit = unit

    @property
    def timestamp(self):
        """
        Gets the timestamp of this MeasureMetadata.


        :return: The timestamp of this MeasureMetadata.
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """
        Sets the timestamp of this MeasureMetadata.


        :param timestamp: The timestamp of this MeasureMetadata.
        :type: str
        """

        self._timestamp = timestamp

    @property
    def dimension(self):
        """
        Gets the timestamp of this MeasureMetadata.


        :return: The timestamp of this MeasureMetadata.
        :rtype: str
        """
        return self._dimension

    @dimension.setter
    def dimension(self, timestamp):
        """
        Sets the timestamp of this MeasureMetadata.


        :param timestamp: The timestamp of this MeasureMetadata.
        :type: str
        """

        self._dimension = dimension

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
